version: '3.8'

services:
  database:
    image: postgres:15.3-alpine3.17
    container_name: DHPF_DB
    volumes:
      - ./DHPF_Data/db/:/var/lib/postgresql/data
      - ./DHPF_Data/initial/:/home/
    restart: always
    environment:
      - POSTGRES_DB=DHPF_db
      - POSTGRES_USER=postgres_DHPF_admin
      - POSTGRES_PASSWORD=postgres_DHPF_password
    tty: true
    ports:
      - "5432:5432"

  server:
    container_name: DHPF_SERVER
    build: ./DHPF_Server
    command: python manage.py runserver 0.0.0.0:8000
    # sh -c "service cron start && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./DHPF_Server:/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=DHPF_db
      - POSTGRES_USER=postgres_DHPF_admin
      - POSTGRES_PASSWORD=postgres_DHPF_password
    tty: true
    depends_on:
      - database
    restart: always

  app:
    container_name: DHPF_WEBAPP
    build: ./DHPF_WebApp
    # command: sh -c "dhpf && npm start"
    volumes:
      - ./DHPF_WebApp/dhpf:/app
    ports:
      - 3000:3000
    tty: true
    restart: always